src/cyw43_ll: Use memmove for operands coincident in memory.
Compiling with gcc 13.2 at -O3 has more aggressive inlining causing
detection of illegal `memcpy` operand overlap cases that were not found by
earlier versions of gcc:

  In function 'cyw43_send_ioctl',
    inlined from 'cyw43_do_ioctl' at lib/cyw43-driver/src/cyw43_ll.c,
    inlined from 'cyw43_set_ioctl_u32' at lib/cyw43-driver/src/cyw43_ll.c,
    inlined from 'cyw43_ll_wifi_on' at lib/cyw43-driver/src/cyw43_ll.c,
  lib/cyw43-driver/src/cyw43_ll.c:772:5: error: 'memcpy' accessing 4 bytes
  at offsets 68 and 68 overlaps 4 bytes at offset 68 [-Werror=restrict]
    772 |     memcpy(self->spid_buf + SDPCM_HEADER_LEN + 16, buf, len);
        |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This commit fixes this issue by using `memmove` instead.